// <auto-generated />
using System;
using AgriTrace.Infrastructure.Sqlserver.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriTrace.Infrastructure.Sqlserver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715030741_UpdateRoleAndOrganizationTypes")]
    partial class UpdateRoleAndOrganizationTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CurrentOrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrganizationDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RootBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchCode")
                        .IsUnique();

                    b.HasIndex("CurrentOrganizationId");

                    b.HasIndex("OrganizationDataModelId");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("Batches", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NewBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NewBatchId");

                    b.ToTable("BatchMerges", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeSourceDataModel", b =>
                {
                    b.Property<Guid>("BatchMergeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BatchMergeId", "SourceBatchId");

                    b.HasIndex("SourceBatchId");

                    b.ToTable("BatchMergeSources", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SourceBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceBatchId");

                    b.ToTable("BatchSplits", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDetailDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SplitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SplitId");

                    b.HasIndex("TargetBatchId");

                    b.ToTable("BatchSplitDetails", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.CategoryDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhóm rau củ quả tươi",
                            IsActive = true,
                            Name = "Rau củ"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các loại cà phê",
                            IsActive = true,
                            Name = "Coffee"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gạo các loại",
                            IsActive = true,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Trái cây tươi",
                            IsActive = true,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thảo mộc và gia vị",
                            IsActive = true,
                            Name = "Herbs"
                        });
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.CertificateDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("InspectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("InspectionId");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.EventTypeDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "HARVEST",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Harvest"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "RECEIVE",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Receive"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "PROCESSING",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Processing"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "PACKAGING",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Packaging"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "TRANSPORT",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Transport"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Code = "DISTRIBUTION",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Distribution"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Code = "RETAIL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Retail"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Code = "INSPECTION",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Inspection"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Code = "RECALL",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Recall"
                        });
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.NotificationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationTypeId");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationTypeDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OrganizationTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "FARM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Agricultural Farm",
                            Name = "Farm"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "PROCESSOR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Processor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "DISTRIBUTOR",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Distributor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "RETAILER",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Retailer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "INSPECTION",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Inspection"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "SYSTEM",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "System"
                        });
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.ProductDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.QualityInspectionDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("InspectorId");

                    b.ToTable("QualityInspections", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.RecallDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("RecallDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RecallDataModelId");

                    b.HasIndex("UserDataModelId");

                    b.ToTable("Recalls", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.SupplyChainEventDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserDataModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("UserDataModelId");

                    b.ToTable("SupplyChainEvents", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.UnitDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", "CurrentOrganization")
                        .WithMany()
                        .HasForeignKey("CurrentOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", null)
                        .WithMany("Batches")
                        .HasForeignKey("OrganizationDataModelId");

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "ParentBatch")
                        .WithMany("ChildBatches")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.ProductDataModel", "Product")
                        .WithMany("Batches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UnitDataModel", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentOrganization");

                    b.Navigation("ParentBatch");

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "NewBatch")
                        .WithMany()
                        .HasForeignKey("NewBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewBatch");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeSourceDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeDataModel", "BatchMerge")
                        .WithMany("Sources")
                        .HasForeignKey("BatchMergeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "SourceBatch")
                        .WithMany()
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatchMerge");

                    b.Navigation("SourceBatch");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "SourceBatch")
                        .WithMany()
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceBatch");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDetailDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDataModel", "Split")
                        .WithMany("Details")
                        .HasForeignKey("SplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "TargetBatch")
                        .WithMany()
                        .HasForeignKey("TargetBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Split");

                    b.Navigation("TargetBatch");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.CertificateDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "Batch")
                        .WithMany("Certificates")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.QualityInspectionDataModel", "Inspection")
                        .WithMany("Certificates")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.NotificationDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationTypeDataModel", "OrganizationType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrganizationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizationType");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.ProductDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.CategoryDataModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", "Organization")
                        .WithMany("Products")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UnitDataModel", "Unit")
                        .WithMany("Products")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.QualityInspectionDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "Batch")
                        .WithMany("Inspections")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.RecallDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "Batch")
                        .WithMany("Recalls")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.RecallDataModel", null)
                        .WithMany("Recalls")
                        .HasForeignKey("RecallDataModelId");

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", null)
                        .WithMany("Recalls")
                        .HasForeignKey("UserDataModelId");

                    b.Navigation("Batch");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.SupplyChainEventDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", "Batch")
                        .WithMany("Events")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.EventTypeDataModel", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", null)
                        .WithMany("Events")
                        .HasForeignKey("UserDataModelId");

                    b.Navigation("Batch");

                    b.Navigation("EventType");

                    b.Navigation("Organization");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", b =>
                {
                    b.HasOne("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchDataModel", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("ChildBatches");

                    b.Navigation("Events");

                    b.Navigation("Inspections");

                    b.Navigation("Recalls");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchMergeDataModel", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.BatchSplitDataModel", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.CategoryDataModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.EventTypeDataModel", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationDataModel", b =>
                {
                    b.Navigation("Batches");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.OrganizationTypeDataModel", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.ProductDataModel", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.QualityInspectionDataModel", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.RecallDataModel", b =>
                {
                    b.Navigation("Recalls");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.UnitDataModel", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AgriTrace.Infrastructure.Sqlserver.Models.UserDataModel", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Notifications");

                    b.Navigation("Recalls");
                });
#pragma warning restore 612, 618
        }
    }
}
